### PR TITLE
Remove Java process handling.

### PR DESCRIPTION
**Pull request by chrisr3**
Removes spawning processes and examining the process environment, and some functionality which uses these things.

### CODE REVIEW

**Review by exFalso — COMMENTED** [review]
Looks good, one thing I'm unsure of is the contentType removal from URLConnection. Is this necessary?

**Comment by chrisr3** [comment]
I removed `contentType` after considering Mike's guidance of "If in doubt, take it out!". And it looked like its main use was supporting HTTP `Content-Type` headers.

**Comment by exFalso** [comment]
Fair enough. I reckon later on we'll see what libraries break that we may potentially want to load for verification, so it's better to remove borderline code

**Review by exFalso — APPROVED** [review]
LGTM 👍

**Pull request merged**
